version: "3.9"

services:
  django:
    build: .
    expose:
      - "8000"
    volumes:
      - static_volume:/config/staticfiles

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/static:ro

  rp-postgres:
    image: postgres:15.2
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - rp-volume:/var/lib/postgresql/data

volumes:
  static_volume:
  rp-volume:
