# Generated by Django 5.2.13 on 2026-04-18 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_parser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategories',
            fields=[
                ('item_category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_category_name', models.CharField(max_length=100, unique=True)),
                ('item_category_description', models.CharField(max_length=255, null=True)),
                ('item_categories_insert_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreNames',
            fields=[
                ('store_name_id', models.IntegerField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=100, unique=True)),
                ('store_name_description', models.CharField(max_length=255, null=True)),
                ('store_names_insert_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Receipt',
            new_name='ReceiptView',
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('item_description', models.CharField(max_length=255, null=True)),
                ('items_insert_datetime', models.DateTimeField(auto_now_add=True)),
                ('category_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items_category_id_fk', to='receipt_parser.itemcategories')),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('store_id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100, unique=True)),
                ('stores_insert_datetime', models.DateTimeField(auto_now_add=True)),
                ('store_name_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stores_name_id_fk', to='receipt_parser.storenames')),
            ],
        ),
    ]
