# Generated by Django 5.2.13 on 2026-04-20 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_parser', '0002_itemcategories_storenames_rename_receipt_receiptview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('payment_method_id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_method_name', models.CharField(max_length=100, unique=True)),
                ('payment_method_description', models.CharField(max_length=255, null=True)),
                ('payment_method_insert_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptResources',
            fields=[
                ('receipt_resource_id', models.IntegerField(primary_key=True, serialize=False)),
                ('original_image_path', models.CharField(max_length=150, unique=True)),
                ('grayscale_image_path', models.CharField(max_length=150, null=True, unique=True)),
                ('visualization_image_path', models.CharField(max_length=150, null=True, unique=True)),
                ('raw_text_json', models.CharField(max_length=150, unique=True)),
                ('receipt_resource_insert_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='itemcategories',
            old_name='item_categories_insert_datetime',
            new_name='item_categorie_insert_datetime',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='items_insert_datetime',
            new_name='item_insert_datetime',
        ),
        migrations.RenameField(
            model_name='storenames',
            old_name='store_names_insert_datetime',
            new_name='store_name_insert_datetime',
        ),
        migrations.RenameField(
            model_name='stores',
            old_name='stores_insert_datetime',
            new_name='store_insert_datetime',
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('receipt_id', models.IntegerField(primary_key=True, serialize=False)),
                ('receipt_datetime', models.DateTimeField()),
                ('receipt_insert_datetime', models.DateTimeField(auto_now_add=True)),
                ('receipt_reference', models.CharField(max_length=100, unique=True)),
                ('receipt_description', models.CharField(max_length=255, null=True)),
                ('item_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items_id_fk', to='receipt_parser.items')),
                ('payment_method_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_methods_id_fk', to='receipt_parser.paymentmethods')),
                ('store_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stores_id_fk', to='receipt_parser.stores')),
                ('receipt_resource_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receipt_resources_id_fk', to='receipt_parser.receiptresources')),
            ],
        ),
    ]
