# Generated by Django 5.2.13 on 2026-04-27 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_parser', '0003_paymentmethods_receiptresources_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='item_id_fk',
        ),
        migrations.CreateModel(
            name='ReceiptItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_datetime', models.DateTimeField(auto_now_add=True)),
                ('item_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items_id_fk', to='receipt_parser.items')),
                ('receipt_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receipt_id_fk', to='receipt_parser.receipt')),
            ],
        ),
    ]
