# Generated by Django 5.2.13 on 2026-04-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_parser', '0004_remove_receipt_item_id_fk_receiptitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
    ]
