# Generated by Django 5.2.13 on 2026-04-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_parser', '0005_alter_items_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='city',
            field=models.CharField(max_length=100),
        ),
    ]
