# Generated by Django 5.2.13 on 2026-04-29 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_parser', '0006_alter_stores_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='category_id_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rel_items_category_id_fk', to='receipt_parser.itemcategories'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_method_id_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rel_payment_methods_id_fk', to='receipt_parser.paymentmethods'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_resource_id_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rel_receipt_resources_id_fk', to='receipt_parser.receiptresources'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='store_id_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rel_stores_id_fk', to='receipt_parser.stores'),
        ),
        migrations.AlterField(
            model_name='receiptitems',
            name='item_id_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rel_items_id_fk', to='receipt_parser.items'),
        ),
        migrations.AlterField(
            model_name='receiptitems',
            name='receipt_id_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rel_receipt_id_fk', to='receipt_parser.receipt'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='store_name_id_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rel_stores_name_id_fk', to='receipt_parser.storenames'),
        ),
    ]
