# Generated by Django 5.2.13 on 2026-04-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_parser', '0007_alter_items_category_id_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptresources',
            name='grayscale_image_path',
            field=models.ImageField(null=True, unique=True, upload_to='receipt_parser/'),
        ),
        migrations.AlterField(
            model_name='receiptresources',
            name='original_image_path',
            field=models.ImageField(unique=True, upload_to='receipt_parser/'),
        ),
        migrations.AlterField(
            model_name='receiptresources',
            name='visualization_image_path',
            field=models.ImageField(null=True, unique=True, upload_to='receipt_parser/'),
        ),
    ]
