# Generated by Django 5.2.13 on 2026-06-09 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_parser', '0008_alter_receiptresources_grayscale_image_path_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReceiptView',
            new_name='ReceiptImageView',
        ),
    ]
