# Generated by Django 5.2.13 on 2026-07-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_parser', '0009_rename_receiptview_receiptimageview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategories',
            name='item_category_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymentmethods',
            name='payment_method_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='receiptresources',
            name='grayscale_image_path',
            field=models.ImageField(null=True, upload_to='receipt_parser/'),
        ),
        migrations.AlterField(
            model_name='receiptresources',
            name='raw_text_json',
            field=models.CharField(max_length=1500, unique=True),
        ),
        migrations.AlterField(
            model_name='receiptresources',
            name='receipt_resource_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='receiptresources',
            name='visualization_image_path',
            field=models.ImageField(null=True, upload_to='receipt_parser/'),
        ),
        migrations.AlterField(
            model_name='storenames',
            name='store_name_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stores',
            name='store_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
