# Generated by Django 5.2.13 on 2026-07-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_parser', '0010_alter_itemcategories_item_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptitems',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
