# Generated by Django 5.2.13 on 2026-07-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_parser', '0011_receiptitems_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptresources',
            name='raw_text_json',
            field=models.CharField(max_length=9000, unique=True),
        ),
    ]
