# Generated by Django 5.2.13 on 2026-07-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_parser', '0012_alter_receiptresources_raw_text_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.FloatField(),
        ),
    ]
