# Generated by Django 5.2.13 on 2026-07-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_parser', '0013_alter_items_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='price',
        ),
        migrations.AddField(
            model_name='receiptitems',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
