# Generated by Django 5.2.13 on 2026-08-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_parser', '0014_remove_items_price_receiptitems_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptresources',
            name='raw_text_json',
            field=models.CharField(max_length=9000),
        ),
    ]
