# Generated by Django 5.2.13 on 2026-08-14 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_parser', '0015_alter_receiptresources_raw_text_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='receipt_image_view_id_fk',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rel_receipt_image_view_id_fk', to='receipt_parser.receiptimageview'),
            preserve_default=False,
        ),
    ]
