# Generated by Django 5.2.13 on 2026-09-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_parser', '0016_receipt_receipt_image_view_id_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
